version: 0.1
phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - error.html
    - favicon.ico
    - react.html
    - styles/*
    - images/*
    - dist/bundle.js
